"""add notification emails to loan

Revision ID: 2931baf344c9
Revises: f057cc843f50
Create Date: 2026-05-22 11:52:19.546010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2931baf344c9'
down_revision = 'f057cc843f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_fixed_emails', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notification_extra_emails', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notification_all_emails', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('notification_all_emails')
        batch_op.drop_column('notification_extra_emails')
        batch_op.drop_column('notification_fixed_emails')

    # ### end Alembic commands ###
