"""add responsible email to loans

Revision ID: 2a01fdeb099c
Revises: 827b03501578
Create Date: 2026-05-25 13:45:38.971051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a01fdeb099c'
down_revision = '827b03501578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel_entrega_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('responsavel_entrega_email')

    # ### end Alembic commands ###
