"""initial

Revision ID: 3a573ea810ea
Revises: 
Create Date: 2026-05-21 15:09:16.864967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a573ea810ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('matricula', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvers_email'), ['email'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('performed_by', sa.String(length=255), nullable=False),
    sa.Column('old_data', sa.Text(), nullable=True),
    sa.Column('new_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('limite_alerta', sa.Integer(), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumables_codigo_interno'), ['codigo_interno'], unique=True)
        batch_op.create_index(batch_op.f('ix_consumables_nome_normalizado'), ['nome_normalizado'], unique=False)

    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=255), nullable=False),
    sa.Column('patrimonio', sa.String(length=255), nullable=True),
    sa.Column('serial', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipments_codigo_interno'), ['codigo_interno'], unique=True)
        batch_op.create_index(batch_op.f('ix_equipments_nome_normalizado'), ['nome_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipments_patrimonio'), ['patrimonio'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipments_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('matricula', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=100), nullable=True),
    sa.Column('gerencia', sa.String(length=255), nullable=True),
    sa.Column('regional', sa.String(length=255), nullable=True),
    sa.Column('equipe', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_matricula'), ['matricula'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_controle', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_entrega_nome', sa.String(length=255), nullable=False),
    sa.Column('responsavel_entrega_matricula', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('data_emprestimo', sa.DateTime(), nullable=True),
    sa.Column('data_prevista_devolucao', sa.DateTime(), nullable=True),
    sa.Column('data_real_devolucao', sa.DateTime(), nullable=True),
    sa.Column('local_utilizacao', sa.String(length=255), nullable=True),
    sa.Column('aprovado', sa.Boolean(), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(), nullable=True),
    sa.Column('rejeitado_em', sa.DateTime(), nullable=True),
    sa.Column('motivo_rejeicao', sa.Text(), nullable=True),
    sa.Column('approval_token', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['approvers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_numero_controle'), ['numero_controle'], unique=True)
        batch_op.create_index(batch_op.f('ix_loans_status'), ['status'], unique=False)

    op.create_table('loan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('consumable_id', sa.Integer(), nullable=True),
    sa.Column('tipo_item', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('quantidade_devolvida', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('devolvido_em', sa.DateTime(), nullable=True),
    sa.Column('devolvido_por', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renewals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('old_due_date', sa.DateTime(), nullable=False),
    sa.Column('new_due_date', sa.DateTime(), nullable=False),
    sa.Column('renewed_by', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('renewals')
    op.drop_table('loan_items')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_status'))
        batch_op.drop_index(batch_op.f('ix_loans_numero_controle'))

    op.drop_table('loans')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_matricula'))

    op.drop_table('users')
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipments_status'))
        batch_op.drop_index(batch_op.f('ix_equipments_patrimonio'))
        batch_op.drop_index(batch_op.f('ix_equipments_nome_normalizado'))
        batch_op.drop_index(batch_op.f('ix_equipments_codigo_interno'))

    op.drop_table('equipments')
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumables_nome_normalizado'))
        batch_op.drop_index(batch_op.f('ix_consumables_codigo_interno'))

    op.drop_table('consumables')
    op.drop_table('audit_logs')
    with op.batch_alter_table('approvers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvers_email'))

    op.drop_table('approvers')
    # ### end Alembic commands ###
