"""add image fields to loan items

Revision ID: 4033fc29bc95
Revises: 2a01fdeb099c
Create Date: 2026-05-25 15:07:33.901295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4033fc29bc95'
down_revision = '2a01fdeb099c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_original_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_items', schema=None) as batch_op:
        batch_op.drop_column('image_original_filename')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
