"""add system users

Revision ID: 490c396f1517
Revises: 4033fc29bc95
Create Date: 2026-05-25 17:05:59.488035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490c396f1517'
down_revision = '4033fc29bc95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_users_email'))

    op.drop_table('system_users')
    # ### end Alembic commands ###
