"""add sync pendings

Revision ID: 7faa531d916d
Revises: 490c396f1517
Create Date: 2026-05-26 08:28:08.486321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7faa531d916d'
down_revision = '490c396f1517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_pendings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_pendings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_pendings_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_pendings_entity_type'), ['entity_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_pendings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_pendings_entity_type'))
        batch_op.drop_index(batch_op.f('ix_sync_pendings_entity_id'))

    op.drop_table('sync_pendings')
    # ### end Alembic commands ###
