"""add excel inventory fields to equipment

Revision ID: 827b03501578
Revises: a3ca7b8d7fb3
Create Date: 2026-05-25 10:22:18.499002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827b03501578'
down_revision = 'a3ca7b8d7fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_planilha', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('regional', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('data_inventario', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('local_armazenagem', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('subestacao_origem', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('emprestado_para_planilha', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('data_emprestimo_planilha', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_equipments_serial'), ['serial'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipments_serial'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('data_emprestimo_planilha')
        batch_op.drop_column('emprestado_para_planilha')
        batch_op.drop_column('subestacao_origem')
        batch_op.drop_column('local_armazenagem')
        batch_op.drop_column('data_inventario')
        batch_op.drop_column('regional')
        batch_op.drop_column('status_planilha')

    # ### end Alembic commands ###
