"""add external pendings

Revision ID: 8c2e15fac124
Revises: ff0ae74f304e
Create Date: 2026-05-26 16:37:01.611177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2e15fac124'
down_revision = 'ff0ae74f304e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_pendings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_pendings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_pendings_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_pendings_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_pendings_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_pendings_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_pendings_status'), ['status'], unique=False)

    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_codigo_equipamento'))
        batch_op.drop_index(batch_op.f('ix_equipment_codigo_interno'))
        batch_op.drop_index(batch_op.f('ix_equipment_nome_normalizado'))
        batch_op.drop_index(batch_op.f('ix_equipment_patrimonio'))
        batch_op.drop_index(batch_op.f('ix_equipment_serial'))
        batch_op.drop_index(batch_op.f('ix_equipment_status'))

    with op.batch_alter_table('loan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_items_equipment_id'))
        batch_op.drop_index(batch_op.f('ix_loan_items_loan_id'))
        batch_op.drop_index(batch_op.f('ix_loan_items_status'))

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_approver_id'))
        batch_op.drop_index(batch_op.f('ix_loans_created_at'))
        batch_op.drop_index(batch_op.f('ix_loans_data_emprestimo'))
        batch_op.drop_index(batch_op.f('ix_loans_data_prevista_devolucao'))
        batch_op.drop_index(batch_op.f('ix_loans_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_equipe'))
        batch_op.drop_index(batch_op.f('ix_users_gerencia'))
        batch_op.drop_index(batch_op.f('ix_users_nome'))
        batch_op.drop_index(batch_op.f('ix_users_regional'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_regional'), ['regional'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_gerencia'), ['gerencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_equipe'), ['equipe'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_data_prevista_devolucao'), ['data_prevista_devolucao'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_data_emprestimo'), ['data_emprestimo'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_approver_id'), ['approver_id'], unique=False)

    with op.batch_alter_table('loan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_items_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_items_equipment_id'), ['equipment_id'], unique=False)

    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_serial'), ['serial'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_patrimonio'), ['patrimonio'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_nome_normalizado'), ['nome_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_codigo_interno'), ['codigo_interno'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_codigo_equipamento'), ['codigo_equipamento'], unique=False)

    with op.batch_alter_table('external_pendings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_pendings_status'))
        batch_op.drop_index(batch_op.f('ix_external_pendings_entity_type'))
        batch_op.drop_index(batch_op.f('ix_external_pendings_entity_id'))
        batch_op.drop_index(batch_op.f('ix_external_pendings_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_external_pendings_action'))

    op.drop_table('external_pendings')
    # ### end Alembic commands ###
