"""add codigo equipamento to equipments

Revision ID: a3ca7b8d7fb3
Revises: 2931baf344c9
Create Date: 2026-05-25 10:08:07.788803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ca7b8d7fb3'
down_revision = '2931baf344c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_equipamento', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_equipments_codigo_equipamento'), ['codigo_equipamento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipments_codigo_equipamento'))
        batch_op.drop_column('codigo_equipamento')

    # ### end Alembic commands ###
