"""add equipment detail fields

Revision ID: f057cc843f50
Revises: e7222f169869
Create Date: 2026-05-22 07:33:49.339562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f057cc843f50'
down_revision = 'e7222f169869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fabricante', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('modelo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tipo_equipamento', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_column('tipo_equipamento')
        batch_op.drop_column('modelo')
        batch_op.drop_column('fabricante')

    # ### end Alembic commands ###
